# https://mise.jdx.dev/configuration.html

[tools]
awscli         = 'latest'
dotnet         = "8.0.406"
helm           = 'latest'
k9s            = 'latest'
kubectl        = 'latest'
kubectx        = 'latest'
pre-commit     = 'latest'
python         = "3.12.9"
terraform      = "1.10"
terraform-docs = 'latest'

[settings]
activate_aggressive = true
trusted_config_paths = [
  '~/Projects',
]

legacy_version_file               = true # enabled by default (unlike asdf)
legacy_version_file_disable_tools = ['python', 'terraform']
not_found_auto_install            = true

experimental = true

[env]
MISE_USE_VERSIONS_HOST=false

# [settings.python]
# compile = false
