on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt update
          sudo apt install -y jq curl git bash
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
      - run: |
          mise install
      - run: |
          pre-commit run --show-diff-on-failure --color=always --all-files
      - run: |
          pre-commit run --show-diff-on-failure --color=always --all-files --hook-stage=manual
